name: irelandstatistics
description: This project aims to demonstrate diverse statistics in Ireland on different end-clients.
publish_to: 'none'
version: 1.0.0+1
repository: https://github.com/freestyletime/IrelandStatistics-Mobile

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.3
  get_it: ^7.6.4
  event_bus: ^2.0.0
  flutter_bloc: ^8.1.3
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.2
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/
